"use client";

import { useState } from "react";

import { adminButton } from "@/features/admin/components/shell/admin-button";
import { ADMIN_NOTE } from "@/features/admin/components/shell/admin-card";
import { AdminField, adminInput } from "@/features/admin/components/shell/admin-field";
import { buildMileTimetable } from "@/lib/events/timetables";
import { cn } from "@/lib/utils";

/**
 * The event window — the only part of {@link EventForm} that has to be a client
 * island, and it earns it twice over.
 *
 * The two windows the series actually runs are one press each rather than four
 * typed digits, and the on-site timetable below re-derives itself from the start
 * time as it is typed. That timetable is not a field: it is generated by
 * `buildMileTimetable()` and stored nowhere, so the only way an admin can see
 * what moving the window does to the public schedule is to be shown it here
 * before saving.
 *
 * `buildMileTimetable` is a pure function over a `"HH:MM"` string (it imports
 * nothing but the event types), so it bundles for the browser — unlike
 * `@/lib/events/registry`, which reaches the database driver. That is why the
 * preset windows arrive as props from the server component above rather than
 * being imported here.
 */

export type WindowPreset = {
  label: string;
  start: string;
  end: string;
};

/**
 * English labels for the generated blocks, keyed by the same `labelKey` the
 * public timetable resolves under `events.timetable`. Restated here because the
 * admin panel is English-only and does not load message catalogues.
 */
const BLOCK_LABEL: Record<string, string> = {
  checkin: "Check-in & bib pickup",
  briefing: "Briefing & warm-up",
  heats: "Mile heats",
  cooldown: "Cool-down",
  awards: "Awards & photos",
};

/** A start time only generates a timetable once it is a complete `HH:MM`. */
const HH_MM = /^([01]\d|2[0-3]):[0-5]\d$/;

export function EventWindowFields({
  start: initialStart,
  end: initialEnd,
  presets,
}: {
  start: string;
  end: string;
  presets: readonly WindowPreset[];
}) {
  const [start, setStart] = useState(initialStart);
  const [end, setEnd] = useState(initialEnd);

  const blocks = HH_MM.test(start) ? buildMileTimetable(start) : null;

  return (
    <>
      <div className="flex flex-wrap items-end gap-2.5">
        <AdminField label="Start" className="w-[110px]">
          <input
            className={adminInput()}
            type="time"
            name="startTime"
            required
            value={start}
            onChange={(e) => setStart(e.target.value)}
            data-event-start
          />
        </AdminField>
        <AdminField label="End" className="w-[110px]">
          <input
            className={adminInput()}
            type="time"
            name="endTime"
            required
            value={end}
            onChange={(e) => setEnd(e.target.value)}
            data-event-end
          />
        </AdminField>
        <div className="flex flex-wrap items-center gap-2 pb-px">
          {presets.map((preset) => {
            const current = preset.start === start && preset.end === end;
            return (
              <button
                key={preset.label}
                type="button"
                className={adminButton(current ? "primary" : "stroke")}
                aria-pressed={current}
                onClick={() => {
                  setStart(preset.start);
                  setEnd(preset.end);
                }}
              >
                {preset.label} {preset.start}–{preset.end}
              </button>
            );
          })}
        </div>
      </div>

      <p className={cn(ADMIN_NOTE, "mt-2 max-w-[78ch]")}>
        The window is what the public event page states, and the start time is what the on-site
        timetable below is generated from — three hours of it, whatever the end time says. The heat
        builder prefills its first heat an hour after the start, so moving the window moves the next
        generated card. Heats already generated are stored times and do not move with it.
      </p>

      <div className="mt-3">
        <p className="font-mono text-[10px] font-medium uppercase tracking-[0.16em] text-admin-muted">
          Generated timetable · not editable
        </p>
        {blocks ? (
          <ul className="mt-2 max-w-[420px] divide-y divide-admin-line rounded-admin border border-admin-line bg-admin-surface-2">
            {blocks.map((block) => (
              <li
                key={block.labelKey}
                className="flex items-baseline justify-between gap-4 px-3 py-2"
              >
                <span className="font-mono text-[12px] text-admin-ink">{block.time}</span>
                <span className="text-[12.5px] text-admin-ink-2">
                  {BLOCK_LABEL[block.labelKey] ?? block.labelKey}
                </span>
              </li>
            ))}
          </ul>
        ) : (
          <p className={cn(ADMIN_NOTE, "mt-2")}>
            Enter a start time as HH:MM to see the schedule the public page will show.
          </p>
        )}
      </div>
    </>
  );
}
