-- ###########################################################################
-- ## RUN THIS BEFORE `npm run db:migrate` — THIS MIGRATION CAN FAIL ON DATA ##
-- ###########################################################################
--
--   npx tsx --env-file=.env.local scripts/check-email-case-dupes.ts
--
-- The last statement below creates a UNIQUE index on lower(email). If two rows
-- already differ only by email casing ("A@x.com" / "a@x.com"), Postgres refuses
-- to build the index and the WHOLE migration rolls back — including the
-- phone_e164 column. That is a clean failure, not corruption, but resolving it
-- is manual (merge or delete the losing account), so find out first. The
-- precheck script is read-only and lists the conflicting rows.
--
-- Then, in order:
--   1. precheck (above) — must report "no case-variant duplicates"
--   2. npm run db:migrate            (Neon branch first, then production)
--   3. npx tsx --env-file=.env.local scripts/backfill-phone-e164.ts
--                                    (dry-run; read the report)
--   4. ALLOW_FIXTURES=1 npx tsx --env-file=.env.local \
--        scripts/backfill-phone-e164.ts --write
--
-- Do not edit this file after it has been applied anywhere — drizzle-kit
-- records its hash.
--
ALTER TABLE "users" ADD COLUMN "phone_e164" text;--> statement-breakpoint
CREATE INDEX "users_phone_e164_idx" ON "users" USING btree ("phone_e164");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_lower_uq" ON "users" USING btree (lower("email"));